[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gpp", "pkg-config", "cairo", "pango", "libjpeg", "giflib", "pixman", "freetype"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
